# Generated by Django 3.2.9 on 2021-12-29 09:44

import django.core.validators
from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('caller_name', models.CharField(max_length=75, verbose_name='Name of the caller')),
                ('caller_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Intersex', 'Intersex')], max_length=9)),
                ('caller_age', models.PositiveIntegerField(error_messages={'required': 'Ensure that age is between 0 and 140 yrs'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(140)])),
                ('caller_phone_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('purpose', models.CharField(choices=[('Food/Financial Assistance', 'Food/Financial Assistance'), ('Psychosocial Support', 'Psychosocial Support'), ('General Inquiry', 'General Inquiry'), ('Membership and Volunteerism', 'Membership and Volunteerism'), ('Seeking Ambulance Services', 'Seeking Ambulance Services'), ('Livelihoods', 'Livelihoods'), ('Reporting Incident', 'Reporting Incident'), ('Covid-19', 'Covid-19'), ('Complaints and Feedback', 'Complaints and Feedback')], max_length=75)),
                ('intervention', models.CharField(choices=[('Advised Accordingly', 'Advised Accordingly'), ('On duty Counsellor', 'On duty Counsellor'), ('Refer to Eplus', 'Refer to Eplus'), ('Not declared', 'Not declared'), ('Refer to Police', 'Refer to Police'), ('Refer to CC', 'Refer to CC'), ('PFA', 'PFA'), ('Refer to C&F Hotline', 'Refer to C&F Hotline'), ('Refer to 1196', 'Refer to 1196'), ('Refer to Chief', 'Refer to Chief')], max_length=75)),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending')], max_length=8)),
                ('incident_date_time', models.DateTimeField(help_text='This field captures the date and time when the incident occured', verbose_name='Date & Time')),
                ('address', models.CharField(help_text='Type in the location / place where the         incident occurred in this field. Try to find out the exact location.             This field automatically updates the map below', max_length=255)),
                ('geolocation', location_field.models.spatial.LocationField(srid=4326)),
                ('county', models.CharField(choices=[('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Mombasa', 'Mombasa'), ("Murang'a", "Murang'a"), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Taita Taveta', 'Taita Taveta'), ('Tana River', 'Tana River'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Trans Nzoia', 'Trans Nzoia'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot')], max_length=18)),
                ('region', models.CharField(max_length=15)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Incident Reporter',
                'verbose_name_plural': 'Incident Reporter',
            },
        ),
        migrations.AddIndex(
            model_name='incidentreporter',
            index=models.Index(fields=['caller_name'], name='incident_re_caller__a476f2_idx'),
        ),
    ]
