# Generated by Django 3.2.9 on 2021-12-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreporter',
            name='intervention',
            field=models.CharField(choices=[('Advised Accordingly', 'Advised Accordingly'), ('On duty Counsellor', 'On duty Counsellor'), ('Ref to Eplus', 'Ref to Eplus'), ('Not declared', 'Not declared'), ('Refer to Police', 'Refer to Police'), ('Ref to CC', 'Ref to CC'), ('PFA', 'PFA'), ('PFA by Desk Officer', 'PFA by Desk Officer'), ('Ref to C&F Hotline', 'Ref to C&F Hotline'), ('Ref to 1196', 'Ref to 1196'), ('Ref to Chief', 'Ref to Chief'), ('Ref to Respective Agency', 'Ref to Respective Agency'), ('Ref to Other', 'Ref to Other'), ('Not declared', 'Not declared')], max_length=75),
        ),
        migrations.AlterField(
            model_name='incidentreporter',
            name='purpose',
            field=models.CharField(choices=[('Food/ Financial Assistance', 'Food/ Financial Assistance'), ('Psychosocial Support (PSS)', 'Psychosocial Support (PSS)'), ('General Inquiry', 'General Inquiry'), ('Membership & Volunteerism', 'Membership & Volunteerism'), ('Seeking Ambulance Services', 'Seeking Ambulance Services'), ('Livelihood', 'Livelihood'), ('Reporting Incident', 'Reporting Incident'), ('Covid-19', 'Covid-19'), ('Complaints & Feedback', 'Complaints & Feedback')], max_length=75),
        ),
    ]
