# Generated by Django 3.2.9 on 2022-01-05 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incident_reporter', '0004_alter_incidentreporter_caller_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreporter',
            name='desk_assistant',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
