# Generated by Django 3.2.9 on 2022-01-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reporter', '0005_incidentreporter_desk_assistant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreporter',
            options={'permissions': [('Can_export_data', 'Can export data')], 'verbose_name': 'Incident Reporter', 'verbose_name_plural': 'Incident Reporter'},
        ),
    ]
