# Generated by Django 3.2.9 on 2022-01-22 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reporter', '0008_alter_incidentreporter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreporter',
            options={'permissions': [('export_data_csv', 'Can export data as a CSV')], 'verbose_name': 'Incident Reporter', 'verbose_name_plural': 'Incident Reporter'},
        ),
        migrations.AlterField(
            model_name='incidentreporter',
            name='caller_age',
            field=models.PositiveIntegerField(blank=True, error_messages={'required': 'Ensure that age is between 0 and 140 yrs'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(140)]),
        ),
    ]
