# Generated by Django 3.2.9 on 2022-01-23 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incident_reporter', '0010_alter_incidentreporter_caller_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreporter',
            name='desk_assistant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
