# Generated by Django 3.2.9 on 2022-06-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reporter', '0015_auto_20220627_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreporter',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
