# Generated by Django 3.2.9 on 2022-06-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reporter', '0016_alter_incidentreporter_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreporter',
            name='caller_name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Name of the caller'),
        ),
    ]
