# Generated by Django 3.2.9 on 2022-06-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reporter', '0017_alter_incidentreporter_caller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreporter',
            name='address',
            field=models.CharField(blank=True, help_text='Type in the location / place where the         incident occurred in this field. Try to find out the exact location.             This field automatically updates the map below', max_length=50, null=True),
        ),
    ]
