# Generated by Django 3.2.9 on 2022-06-28 11:16

import django.core.validators
from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reporter', '0018_alter_incidentreporter_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreporter',
            name='address',
            field=models.CharField(blank=True, help_text='Type in the location / place where the         incident occurred in this field. Try to find out the exact location. This field automatically updates the map below', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreporter',
            name='caller_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreporter',
            name='caller_phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254712345678'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='incidentreporter',
            name='county',
            field=models.CharField(blank=True, choices=[('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Mombasa', 'Mombasa'), ("Murang'a", "Murang'a"), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Taita Taveta', 'Taita Taveta'), ('Tana River', 'Tana River'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Trans Nzoia', 'Trans Nzoia'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreporter',
            name='geolocation',
            field=location_field.models.spatial.LocationField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='incidentreporter',
            name='intervention',
            field=models.CharField(choices=[('On duty Counsellor', 'On duty Counsellor'), ('Advised accordingly', 'Advised accordingly'), ('Ref to Police', 'Ref to Police'), ('Ref to CC', 'Ref to CC'), ('Ref to Eplus', 'Ref to Eplus'), ('Ref to Other', 'Ref to Other'), ('Ref to Respective Agency', 'Ref to Respective Agency'), ('Ref to C&F Hotline', 'Ref to C&F Hotline'), ('Ref to Chief', 'Ref to Chief'), ('Not declared', 'Not declared'), ('PFA by Desk Officer', 'PFA by Desk Officer'), ('PFA', 'PFA'), ('Ref to 1196', 'Ref to 1196'), ('Ref to 719', 'Ref to 719'), ('Not declared', 'Not declared')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreporter',
            name='purpose',
            field=models.CharField(choices=[('Psychosocial Support (PSS)', 'Psychosocial Support (PSS)'), ('Livelihood', 'Livelihood'), ('General Inquiry', 'General Inquiry'), ('Reporting Incident', 'Reporting Incident'), ('Membership & Volunteerism', 'Membership & Volunteerism'), ('Seeking Ambulance Services', 'Seeking Ambulance Services'), ('Covid-19', 'Covid-19'), ('Complaints & Feedback', 'Complaints & Feedback'), ('Food/ Financial Assistance', 'Food/ Financial Assistance'), ('Testing 1199 Hotline', 'Testing 1199 Hotline'), ('Infrastructural Damage', 'Infrastructural Damage'), ('TERA Messages', 'TERA Messages'), ('Reporting RTA', 'Reporting RTA'), ('SGBV', 'SGBV')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreporter',
            name='region',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreporter',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending')], max_length=8, null=True),
        ),
    ]
