# Generated by Django 3.2.9 on 2022-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situation_reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationreporter',
            name='scene',
            field=models.CharField(max_length=150, verbose_name='Address where the incident occured'),
        ),
    ]
