# Generated by Django 3.2.9 on 2022-05-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situation_reporter', '0002_alter_situationreporter_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationreporter',
            name='krcs_response',
            field=models.TextField(),
        ),
    ]
