# Generated by Django 3.2.9 on 2022-06-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situation_reporter', '0004_alter_situationreporter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationreporter',
            name='type',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Road accident', 'Road accident'), ('Explosions', 'Explosions'), ('Armed conficts', 'Armed conficts'), ('Collapsed building', 'Collapsed building'), ('Sea/Lake Incidents', 'Sea/Lake Incidents'), ('Floods', 'Floods'), ('Drought', 'Drought'), ('Hail storms', 'Hail storms'), ('Land movement', 'Land movement'), ('Terror attacks', 'Terror attacks'), ('Criminal acts', 'Criminal acts'), ('Protest', 'Protest'), ('School Fires', 'School Fires'), ('Other', 'other')], max_length=150, verbose_name='Type of the incident'),
        ),
    ]
